using System.Numerics;
namespace CombatSimulator.Effects.BodyFluids.Surface;
// Native pose/topology input adapter only. All liquid solvers and geometry producers are linked unchanged.
public sealed class CharacterFluidSurface {
 const int W=8,H=16; readonly Vector3[] local; readonly (int A,int B,int C)[] faces;
 public uint Generation {get;set;}=1; public uint PoseRevision {get;private set;}=1; public bool HasSurface=>true; public bool BudgetExhausted {get;set;}
 public int TriangleTestsThisFrame {get;private set;} public string WalkStatus=>"Fixture"; public string OutletStatus=>"Fixture"; public string LipOutletStatus=>"Fixture";
 public Matrix4x4 Transform=Matrix4x4.Identity, Previous=Matrix4x4.Identity; public int MouthTriangle=3; public Vector3 MouthBary=new(.3f,.3f,.4f);
 public CharacterFluidSurface(int panels=1){local=new Vector3[(W+1)*(H+1)*panels];faces=new (int,int,int)[W*H*2*panels];for(int panel=0;panel<panels;panel++){int vo=panel*(W+1)*(H+1),fo=panel*W*H*2;for(int y=0;y<=H;y++)for(int x=0;x<=W;x++)local[vo+y*(W+1)+x]=new(panel*2+(x-W/2)*.02f,1.2f-y*.045f,0);for(int y=0;y<H;y++)for(int x=0;x<W;x++){int v=vo+y*(W+1)+x,t=fo+(y*W+x)*2;faces[t]=(v,v+W+1,v+1);faces[t+1]=(v+1,v+W+1,v+W+2);}}} public void BeginFrame(Matrix4x4 pose,bool budget=false){Previous=Transform;Transform=pose;PoseRevision++;BudgetExhausted=budget;TriangleTestsThisFrame=0;}
 public bool TryGetMouthAnchor(out FluidSurfaceAnchor anchor){anchor=new(Generation,MouthTriangle,MouthBary);return !BudgetExhausted;}
#if CURRENT
 public bool TryGetOutletAnchor(CombatSimulator.BodyFluidOutletSettings site,out FluidSurfaceAnchor anchor){bool valid=TryGetMouthAnchor(out anchor);if(faces.Length>256)anchor.Triangle+=(int)site.Kind*256;return valid;}
 public string GetOutletStatus(CombatSimulator.BodyFluidOutletKind kind)=>"Fixture";
#endif
 public bool TryGetDiagnosticTriangle(FluidSurfaceAnchor anchor,out Vector3 a,out Vector3 b,out Vector3 c,out Vector3 normal){a=b=c=normal=default;if(BudgetExhausted||anchor.Generation!=Generation||anchor.Triangle<0||anchor.Triangle>=faces.Length)return false;TriangleTestsThisFrame++;var f=faces[anchor.Triangle];a=Vector3.Transform(local[f.A],Transform);b=Vector3.Transform(local[f.B],Transform);c=Vector3.Transform(local[f.C],Transform);normal=Vector3.Normalize(Vector3.Cross(b-a,c-a));return true;}
 public bool TryGetTriangleVertexIds(uint generation,int triangle,out int a,out int b,out int c){a=b=c=-1;if(generation!=Generation||triangle<0||triangle>=faces.Length)return false;var f=faces[triangle];a=f.A;b=f.B;c=f.C;return true;}
 public bool TryEvaluate(FluidSurfaceAnchor anchor,out FluidSurfaceSample sample){sample=default;if(!TryGetDiagnosticTriangle(anchor,out var a,out var b,out var c,out var n))return false;var f=faces[anchor.Triangle];Vector3 p=a*anchor.Barycentric.X+b*anchor.Barycentric.Y+c*anchor.Barycentric.Z;Vector3 lp=local[f.A]*anchor.Barycentric.X+local[f.B]*anchor.Barycentric.Y+local[f.C]*anchor.Barycentric.Z;sample=new(p,n,(p-Vector3.Transform(lp,Previous))*60);return true;}
 public bool TryGetMaterialCoordinate(FluidSurfaceAnchor anchor,out Vector2 uv){uv=default;if(anchor.Triangle<0||anchor.Triangle>=faces.Length)return false;var f=faces[anchor.Triangle];var p=local[f.A]*anchor.Barycentric.X+local[f.B]*anchor.Barycentric.Y+local[f.C]*anchor.Barycentric.Z;uv=new(p.X,p.Y);return true;}
 public bool TryGetAdjacentTriangle(FluidSurfaceAnchor anchor,int edge,out FluidSurfaceAnchor neighbor,out float length){neighbor=default;length=0;var f=faces[anchor.Triangle];int a=edge==0?f.B:edge==1?f.A:f.A,b=edge==0?f.C:edge==1?f.C:f.B;length=Vector3.Distance(local[a],local[b]);for(int i=0;i<faces.Length;i++){if(i==anchor.Triangle)continue;var other=faces[i];if((other.A==a||other.B==a||other.C==a)&&(other.A==b||other.B==b||other.C==b)){neighbor=new(Generation,i,new(1f/3));return true;}}return false;}
 public FluidSurfaceAnchor[] GetAdjacentTriangles(FluidSurfaceAnchor source,int max){List<FluidSurfaceAnchor> result=new(){source};HashSet<int> seen=new(){source.Triangle};for(int i=0;i<result.Count&&result.Count<max;i++)for(int e=0;e<3&&result.Count<max;e++)if(TryGetAdjacentTriangle(result[i],e,out var next,out _)&&seen.Add(next.Triangle))result.Add(next);return result.ToArray();}
 static Vector3 Bary(Vector3 p,Vector3 a,Vector3 b,Vector3 c){var v0=b-a;var v1=c-a;var v2=p-a;float d00=Vector3.Dot(v0,v0),d01=Vector3.Dot(v0,v1),d11=Vector3.Dot(v1,v1),d20=Vector3.Dot(v2,v0),d21=Vector3.Dot(v2,v1),den=d00*d11-d01*d01;float v=(d11*d20-d01*d21)/den,w=(d00*d21-d01*d20)/den;return new(1-v-w,v,w);}
 public bool TryWalk(ref FluidSurfaceAnchor anchor,Vector3 displacement,out FluidSurfaceSample sample){sample=default;if(!TryEvaluate(anchor,out sample))return false;Vector3 target=sample.Position+displacement-sample.Normal*Vector3.Dot(displacement,sample.Normal);for(int step=0;step<8;step++){if(!TryGetDiagnosticTriangle(anchor,out var a,out var b,out var c,out _))return false;var bary=Bary(target,a,b,c);if(bary.X>=-1e-6&&bary.Y>=-1e-6&&bary.Z>=-1e-6){anchor.Barycentric=bary;return TryEvaluate(anchor,out sample);}int edge=bary.X<bary.Y?(bary.X<bary.Z?0:2):(bary.Y<bary.Z?1:2);if(!TryGetAdjacentTriangle(anchor,edge,out var next,out _))return false;anchor=next;}return false;}
 public bool TryContact(Vector3 start,Vector3 end,float radius,out FluidSurfaceAnchor anchor,out FluidSurfaceSample sample,out float fraction){anchor=default;sample=default;fraction=1;if(BudgetExhausted)return false;bool found=false;for(int i=0;i<faces.Length;i++){var candidate=new FluidSurfaceAnchor(Generation,i,default);if(!TryGetDiagnosticTriangle(candidate,out var a,out var b,out var c,out var n))continue;float d0=Vector3.Dot(start-a,n)-radius,d1=Vector3.Dot(end-a,n)-radius;if(d0<0||d1>0||d0-d1<1e-9)continue;float t=d0/(d0-d1);if(t>=fraction)continue;Vector3 p=Vector3.Lerp(start,end,t)-n*radius;var bary=Bary(p,a,b,c);if(bary.X<0||bary.Y<0||bary.Z<0)continue;candidate.Barycentric=bary;anchor=candidate;fraction=t;found=TryEvaluate(candidate,out sample);}return found;}
}




